### ISSUE TITLE
Runs too fast + mistake in pypi.org documentation

### ISSUE THREAD

**Issue by phennessey** [MisterBrash/unicornhatsimulator#1]
This runs WAY too fast on my machine. Your implementation of pygame needs to have a delay added to get a consistent framerate. I recommend this change:

```
def show(self):
    self.screen.fill((0, 0, 0))
    self.draw()
    clock = pygame.time.Clock()
    pygame.display.flip()
    clock.tick(100)
```

Also, your documentation on https://pypi.org/project/unicornhatsimulator/ uses the wrong module name to launch the simulator. Your description says to add this to the code to the script you want to launch:
```
from unicorn_hat_sim import unicornhathd as unicorn
```
But "unicorn_hat_sim" is not the right module title. It needs to say:
```
from unicornhatsimulator import unicornhathd as unicorn
```

You should also point out that the alias name "unicorn" should be changed to match whatever alias is used in the script in question. Not every unicornhathd script uses "unicorn" as the alias.

Love this module, BTW! I am doing some graphic work on my machine, which makes development on the unicorn hat HD much easier to test. Thanks!

**Comment by MisterBrash** [comment]
@ophello Thanks for all this. I did not author the original code (I know almost zero about PyGame). I'm also not a game or graphics programmer so the speed at which it runs was fine for my students and I - we're running this simulator in replit.com projects.

The original show( ) function was part of the unicorn_hat_sim project, which is also why there is that typo in my pypi project. 

My students were using the sleep() function from the time module in order to pause between updates to the screen. This is how it is done on the real UnicornHatHD in our classroom (intro to programming). We are fine continuing that in the simulator.

As for your suggested delay, I'm assuming that will cause the simulator to run slower on all machines, including ones with a slower refresh than yours. That would not be ideal (if it's the case). We'll probably stick to the sleep( ) function so that we have full control over the timing between frames. That being said - you are VERY welcome to correct me on all of this. I'm a business / logic programmer, not a game programmer (and even then I'm actually a high school teacher, not a programmer).

To be honest, this was a quick pet-project fix so that I could implement the set_all( ) function and fix the clear( ) function.
Updating a project on pypi with something as simple as that typo will probably take me longer to fix than is necessary... don't be shocked if I never fix it. I had a hell of a time following the instructions to even get that project uploaded to pypi and I had to delete it a million times and rename the files over and over because they don't let you use the same filename or version number or whatever when you upload. Pain in the bum. That was a month ago and now I forget all the commands to setup the package and upload it to pypi. So...  maybe I'll get to it eventually.

Ok well that's more info than you probably needed. Cheers!

**Comment by MisterBrash** [comment]
I will be updating the README on PyPi once I upload the newest version (many many updates). As for the speed - I will not be adding a refresh speed to the simulator itself. On the Raspberry Pi units, the programmer has to manage the speed using the `sleep()` function. It runs faster on a 3B+ versus a 4B, etc... I want to keep that for now. Who knows, maybe I'll change my mind.
